#!/bin/bash

set -eu

# return as there is no message
if [ -z $(sed "s/^;.*//" $1) ]; then exit 0; fi
# return as it has been processed before
if [ $(head -c1 $1) = "#" -o $(head -c6 $1) = "fixup!" ]; then exit 0; fi

branch_name=$(git branch --show-current)
message=

if echo ${branch_name} |grep "^issues/[0-9]*" > /dev/null; then
  issue_no=$(echo ${branch_name} | sed "s|issues/\([0-9]*\).*|\\1|")
  message="#${issue_no}";
fi
if echo ${branch_name} |grep "^issues/[^/]*/[^/]*/[0-9]*" > /dev/null; then
  repository=$(echo ${branch_name} | sed "s|issues/\([^/]*/[^/]*\).*|\\1|")
  issue_no=$(echo ${branch_name} | sed "s|issues/[^/]*/[^/]*/\([0-9]*\).*|\\1|")
  message="${repository}#${issue_no}";
fi

if [ -z ${message} ]; then exit 0; fi
echo "${message} $(cat $1)" > $1

if [ -e ./.git/hooks/commit-msg ]; then
  ./.git/hooks/commit-msg "$@"
fi
