#!/bin/bash

set -eu

remote=$1
for commit in `git rev-list $(git branch --show-current) --not --remotes=${remote}`; do
    # If the commit is written by me and not PR merge
    if [ "`git log --format='%ae' ${commit}^!`" == "`git config user.email`" ] && \
       [[ "`git log --format='%s' ${commit}^!`" != Merge\ pull\ request* ]] && \
       [[ "`git log --format='%s' ${commit}^!`" != Merge\ branch* ]]; then
        git log --format='%B' ${commit}^! -n1|xargs -0 -I {} cog verify {}
    fi
done

if [ -e ./.git/hooks/pre-push ]; then
    ./.git/hooks/pre-push "$@"
fi
