#!/bin/bash

set -eu

commit_file=$1
commit_source=${2:-}

# only add message if this commit is not linked to any commit already
if [[ -z "${commit_source}" ]]; then
    branch_name=$(git branch --show-current)
    message=

    if echo ${branch_name} |grep "^issues/" > /dev/null; then
        # Github Format
        if echo ${branch_name} |grep "^issues/[0-9]*" > /dev/null; then
            issue_no=$(echo ${branch_name} | sed "s|issues/\([0-9]*\).*|\\1|")
            message="#${issue_no}";
        fi
        if echo ${branch_name} |grep "^issues/[^/]*/[^/]*/[0-9]*" > /dev/null; then
            repository=$(echo ${branch_name} | sed "s|issues/\([^/]*/[^/]*\).*|\\1|")
            issue_no=$(echo ${branch_name} | sed "s|issues/[^/]*/[^/]*/\([0-9]*\).*|\\1|")
            message="${repository}#${issue_no}";
        fi

    elif echo ${branch_name} |grep "^feature/" > /dev/null; then
        # Jira Format
        issue_no=$(echo ${branch_name} | sed "s|feature/\([a-zA-Z]\+-[0-9]*\).*|\\1|")
        message="${issue_no}:"
    fi

    if [ -z ${message} ]; then exit 0; fi
    echo "${message} $(cat ${commit_file})" > ${commit_file}
fi

if [ -e ./.git/hooks/prepare-commit-msg ]; then
    ./.git/hooks/prepare-commit-msg "$@"
fi
